[package]
edition = "2021"
name = "remote_hut"
version = "0.1.0"

[[bin]]
name = "remote_hut"
path = "src/main.rs"

[lib]
name = "remote_hut"
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["uuid", "secrets", "json"] }
