[default]
template_dir = "src/views"
directus_token = "wd2PA-KBIK3nVlz3veakgoEKhv2-W4p5"
directus_api_url = "https://remotehut.directus.app"
clockify_token = "YTVjMjZhYzgtNDBkZS00YTEyLTg5MTctODQ1OTFiMjQ3MTYw"
log_level = "normal"
secret_key = "m5TSfjng9pCq2J4eWwX60zH9fnk7YuupqztBx4jEEhs="
